version: '3'

services:
  php-fpm:
    container_name: phpfpm
    build:
      context: ./php-fpm
      args:
        group_name: app
        group_id: 1000
        user_name: app
        user_id: 1000
        PHP_IMAGE: ${PHP_IMAGE}
    environment:
      COMPOSER_AUTH: ${COMPOSER_AUTH}
      BLACKFIRE_AGENT_SOCKET: tcp://blackfire:8707
    volumes:
      - ./magento:/var/www/html
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  web:
    container_name: web
    build: ./web
    volumes:
      - ./magento:/var/www/html
    expose:
      - 8080
    depends_on:
      - php-fpm
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=magentodb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./magento:/var/www/html
  elasticsearch:
    image: elasticsearch:7.17.13
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  redis:
    image: redis:7.0
    ports:
      - 6379:6379
  varnish:
    image: varnish:7.1
    container_name: varnish
    ports:
      - 80:80
    depends_on:
      - web
    environment:
      - VARNISH_SIZE=256M
      - VARNISH_HTTP_PORT=80
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    command: [ "varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-a", ":80", "-s", "malloc,256m" ]
  blackfire:
    image: blackfire/blackfire:2
    environment:
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  mysql_data:
    driver: local